- name: variables from files
  hosts: mongodb #managing the ansible server itself
  become: yes
  vars_files:
  - Variables.yaml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "we are learning {{NAME}}, Duration is : {{DURATION}} , Trainer is : {{TRAINER}}"