- name: ansible variable data types
  hosts: localhost
  vars:
  - AGE:30
  - NAME: "sivakumar"
  - isDevops: true
  - Skills: #list
    - DevOps
    - AWS
    - Docker
  - EXPERIENCE: #MAP
      Devops: 7
      AWS: 5
      Docker: 4
    tasks:
    - name: print number variable
      ansible.builtin.debug:
        msg: "{{AGE}}"
    - name: print String variable
      ansible.builtin.debug:
        msg: "{{NAME}}" 
    - name: print Boolean variable
      ansible.builtin.debug:
        msg: "{{isDevops}}" 
    - name: print List variable
      ansible.builtin.debug:
        msg: "{{Skills}}" 
    - name: print String variable
      ansible.builtin.debug:
        msg: "{{Experience}}" 
